<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>default-value-setting</name>
  <uuid>eca50b05-fd07-4f51-99e6-0524f425c23a</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set 'the name' to "Jones" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
